### ISSUE TITLE
[MCH] Feature: an identical #55, but when it won't trigger at all, unless Reassemble is active

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/MyDalamudPlugins#25] opened 2021-12-14 02:52 UTC
An identical feature as 55, where is adds drill/air onto main combo when reassemble is active.

The current one adds it if reassemble is active OR on cooldown. I would like this to ONLY activate if Reassemble is active

**Comment by Codemned** [comment] 2021-12-14 03:56
I'll look into that.

**Comment by sauronshotdogs** [comment] 2021-12-14 04:20
Thanks!

**Comment by Codemned** [comment] 2021-12-14 04:21
I need to you clarify for me, What exactly do you want it to do?

**Comment by Codemned** [comment] 2021-12-14 05:03
I have a preliminary fix but I can't test Machinist at a higher level.

**Comment by sauronshotdogs** [comment] 2021-12-14 06:14
Mine is 80, but that will work for this request

**Comment by sauronshotdogs** [comment] 2021-12-14 09:29
It works great, thanks!

**Comment by sauronshotdogs** [comment] 2021-12-14 13:31
Would it be possible to make this work synched?

Before 76 Air Anchor is Hot Shot.

Same goes for #55

**Comment by Codemned** [comment] 2021-12-14 13:42
![mch](https://user-images.githubusercontent.com/95727084/146009410-38841279-dc4b-472b-89b3-ade4bb42bad6.png)
#54??

**Comment by sauronshotdogs** [comment] 2021-12-14 13:48
Dude, I am just retarded when it comes to numbers today. I ofc mean 55, sorry.

I have referred to the wrong number each and every single time today.

To avoid any confusion, I am referring to the Drill/Air Anchor feature.

**Comment by Codemned** [comment] 2021-12-14 14:27
I've written a fix for #56 but #55 is working as intended?

**Comment by sauronshotdogs** [comment] 2021-12-14 14:32
Yeah, again I managed to fuck up numbers. Thanks a lot for managing to navigate through my requests.

**Comment by Codemned** [comment] 2021-12-14 14:33
So just the issue with #56 then?

**Comment by sauronshotdogs** [comment] 2021-12-14 14:37
Yes. Thanks a bunch!

**Comment by Codemned** [comment] 2021-12-14 14:37
I've pushed the fix wait for update to Release.

**Comment by sauronshotdogs** [comment] 2021-12-14 14:53
Awesome, thanks again!

**Closed as completed** 2021-12-15 06:56 UTC
